=== 7H3LaughingMan/KCD2-Game-Data/Data/Libs/Storm/storm.dtd
<?xml version="1.0" standalone="yes" ?>

<!ELEMENT storm (customSelectors?,rules?) >
<!ELEMENT customSelectors (customSelector*) >
<!ATTLIST customSelector name CDATA #IMPLIED mode CDATA #IMPLIED >


<!ELEMENT rules (rule*)>

<!ELEMENT rule (selectors,operations)>
<!ATTLIST rule name CDATA #IMPLIED >


<!ELEMENT operations (addRole*,removeRole*)>

<!ELEMENT selectors (not|or|and|hasFaction|hasGender|hasHobby|hasName|hasShop|hasSuperfaction)*>
<!ELEMENT customSelector (not|or|and|hasFaction|hasGender|hasHobby|hasName|hasShop|hasSuperfaction)*>
<!ELEMENT or (not|or|and|hasFaction|hasGender|hasHobby|hasName|hasShop|hasSuperfaction)* >
<!ELEMENT and (not|or|and|hasFaction|hasGender|hasHobby|hasName|hasShop|hasSuperfaction)* >
<!ELEMENT not (not|or|and|hasFaction|hasGender|hasHobby|hasName|hasShop|hasSuperfaction)* >

<!ELEMENT hasFaction EMPTY >
<!ATTLIST hasFaction faction CDATA #IMPLIED >
<!ELEMENT hasGender EMPTY >
<!ATTLIST hasGender gender CDATA #IMPLIED >
<!ELEMENT hasHobby EMPTY >
<!ATTLIST hasHobby hobby CDATA #IMPLIED >
<!ELEMENT hasShop EMPTY >
<!ELEMENT hasName EMPTY >
<!ATTLIST hasName name CDATA #IMPLIED >

<!ELEMENT addRole EMPTY>
<!ATTLIST addRole name CDATA #IMPLIED >
<!ELEMENT removeRole EMPTY>
<!ATTLIST removeRole name CDATA #IMPLIED >

=== 7H3LaughingMan/KCD2-Game-Data/Data/Libs/Storm/roles/quests/hladAZmar.xml
<?xml version="1.0"?>
<!DOCTYPE storm SYSTEM "..\storm.dtd">
<storm>
	<rules>
	
		<rule name="hladAZmar_skirmishOverride_init">
			<selectors>
				<or>
					<hasName name="tkop_ptacek" />
					<hasName name="kcer_kubenka" />
					<hasName name="kkut_samuel" />
				</or>
			</selectors>
			<operations>
				<addRole name="PROTISTRANA" />
			</operations>
		</rule>
		
		<rule name="hladAZmar_skirmishOverride_idle">
			<selectors>
				<or>
					<hasName name="kcer_kubenka" />
					<hasName name="kkut_samuel" />
					<hasName name="oblehaniSuchdole_janek" />
					<hasName name="oblehaniSuchdole_jaroslav" />
					<hasName name="tneb_mikes" />
					<hasName name="tneb_kozlik" />
					<hasName name="ksuc_dobros" />
					<hasName name="ksuc_wolfram" />
					<hasName name="hladAZmar_battle_westPalisade_alternateFriend_1" />
					<hasName name="hladAZmar_battle_westPalisade_alternateFriend_2" />
				</or>
			</selectors>
			<operations>
				<addRole name="CLEN_JINDROVY_JEDNOTKY" />
			</operations>
		</rule>
		
		<rule name="hladAZmar_guardNearRoom">
			<selectors>
				<hasName name="hladAZmar_guardNearFrenczlovaRoom" />
			</selectors>
			<operations>
				<addRole name="STRAZ_PRED_POKOJEM" />
			</operations>
		</rule>
	
		<rule name="hladAZmar_beforeGoingToTower">
			<selectors>
				<or>
					<hasName name="kcer_kubenka" />
					<hasName name="kkut_samuel" />
					<hasName name="oblehaniSuchdole_janek" />
					<hasName name="oblehaniSuchdole_jaroslav" />
					<hasName name="tneb_mikes" />
					<hasName name="tneb_kozlik" />
					<hasName name="ksuc_dobros" />
					<hasName name="ksuc_wolfram" />
					<hasName name="hladAZmar_battle_westPalisade_alternateFriend_1" />
					<hasName name="hladAZmar_battle_westPalisade_alternateFriend_2" />
				</or>
			</selectors>
			<operations>
				<addRole name="VOJAK_KRICI_PRI_ZTECI_NA_VEZ" />
			</operations>
		</rule>
		
		<rule name="hladAZmar_frenclova">
			<selectors>
				<hasName name="ksuc_gertaFrenczlova" />
			</selectors>
			<operations>
				<addRole name="FRENCLOVA" />
			</operations>
		</rule>
		
		
		<rule name="hladAZmar_hansZUher">
			<selectors>
				<hasName name="kmis_hansZUher" />
			</selectors>
			<operations>
				<addRole name="HANS_UHER" />
			</operations>
		</rule>
		
		<rule name="hladAZmar_horseGroom">
			<selectors>
				<hasName name="ksuc_man_20" />
			</selectors>
			<operations>
				<addRole name="PODKONI_SUCHDOL" />
			</operations>
		</rule>

		<rule name="hladAZmar_guards">
			<selectors>
				<hasName name="hladAZmar_beforeBattle_guard*" />
				<hasName name="hladAZmar_prepareToLeave_guard**" />
			</selectors>
			<operations>
				<addRole name="STRAZNY_ZATYKANI" />
			</operations>
		</rule>

		<rule name="hladAZmar_hungryGuard_1">
			<selectors>
				<hasName name="hladAZmar_beforeBattle_guard7" />
			</selectors>
			<operations>
				<addRole name="HLADOVA_STRAZ_SUCHDOL_2" />
			</operations>
		</rule>

		<rule name="hladAZmar_hungryGuard_2">
			<selectors>
				<hasName name="hladAZmar_beforeBattle_guard9" />
			</selectors>
			<operations>
				<addRole name="HLADOVA_STRAZ_SUCHDOL_1" />
			</operations>
		</rule>

		<rule name="hladAZmar_hungryQuestioning">
			<selectors>
				<or>
					<hasName name="tneb_zizka" />
					<hasName name="tneb_mikes" />
					<hasName name="tneb_kozlik" />
					<hasName name="ksuc_petr" />
					<hasName name="ksuc_frenczl" />
					<hasName name="kcer_kubenka" />
					<hasName name="kkut_samuel" />
					<hasName name="ksuc_dobros" />
					<hasName name="ksuc_wolfram" />
					<hasName name="tneb_bohuta" />
					<hasName name="oblehaniSuchdole_janek" />
					<hasName name="oblehaniSuchdole_jaroslav" />
					<hasName name="ksuc_man_1" />
					<hasName name="ksuc_man_17" />
					<!-- <hasName name="ksuc_man_2" />	herec neprijede-->
					<hasName name="ksuc_man_20" />
					<hasName name="ksuc_man_3" />
					<hasName name="ksuc_man_34" />
					<hasName name="hladAZmar_beforeBattle_guard10" />
					<hasName name="hladAZmar_beforeBattle_guard5" />	
					<hasName name="hladAZmar_beforeBattle_guard11" />	
					<hasName name="hladAZmar_beforeBattle_guard20" />	
					<hasName name="hladAZmar_beforeBattle_guard13" />	
					<hasName name="hladAZmar_beforeBattle_guard14" />	
					<hasName name="hladAZmar_beforeBattle_guard16" />		
					<hasName name="hladAZmar_beforeBattle_guard6" />	
					<hasName name="hladAZmar_beforeBattle_guard2" />	
					<hasName name="hladAZmar_beforeBattle_guard17" />	
					<hasName name="hladAZmar_beforeBattle_guard21" />	
					<hasName name="hladAZmar_beforeBattle_guard3" />	
					<hasName name="hladAZmar_beforeBattle_guard12" />	
					<hasName name="hladAZmar_beforeBattle_guard1" />	
					<hasName name="hladAZmar_beforeBattle_guard19" />
					<hasName name="hladAZmar_beforeBattle_guard18" />
					<hasName name="hladAZmar_beforeBattle_guard22" />
					<hasName name="hladAZmar_beforeBattle_guard4" />
					<hasName name="hladAZmar_beforeBattle_guard7" />
					<hasName name="hladAZmar_beforeBattle_guard8" />
					<hasName name="hladAZmar_graveDigger" />
				</or>
			</selectors>
			<operations>
				<addRole name="OBLEHANI_DOTAZY_NA_JIDLO" />
			</operations>
		</rule>

		<rule name="hladAZmar_hungryQuestioning_refusal_man">
			<selectors>
				<or>
					<!-- <hasName name="ksuc_man_1" />	herec neprijede-->
					<hasName name="ksuc_man_17" />
					<!-- <hasName name="ksuc_man_2" />	herec neprijede-->
					<hasName name="hladAZmar_beforeBattle_guard10" />
					<hasName name="hladAZmar_beforeBattle_guard5" />	
					<hasName name="hladAZmar_beforeBattle_guard11" />	
					<hasName name="hladAZmar_beforeBattle_guard20" />	
					<hasName name="hladAZmar_beforeBattle_guard13" />	
					<hasName name="hladAZmar_beforeBattle_guard14" />	
					<hasName name="hladAZmar_beforeBattle_guard16" />		
					<hasName name="hladAZmar_beforeBattle_guard6" />	
					<hasName name="hladAZmar_beforeBattle_guard2" />	
					<hasName name="hladAZmar_beforeBattle_guard17" />	
					<hasName name="hladAZmar_beforeBattle_guard21" />	
					<hasName name="hladAZmar_beforeBattle_guard3" />	
					<hasName name="hladAZmar_beforeBattle_guard12" />	
					<hasName name="hladAZmar_beforeBattle_guard1" />	
					<hasName name="hladAZmar_beforeBattle_guard19" />
					<hasName name="hladAZmar_beforeBattle_guard18" />
					<hasName name="hladAZmar_beforeBattle_guard22" />
					<hasName name="hladAZmar_beforeBattle_guard4" />
					<hasName name="hladAZmar_beforeBattle_guard7" />
					<hasName name="hladAZmar_beforeBattle_guard8" />
					<hasName name="hladAZmar_graveDigger" />
				</or>
			</selectors>
			<operations>
				<addRole name="MUZ_SUCHDOL_O_JIDLE" />
			</operations>
		</rule>

		<rule name="hladAZmar_hungryQuestioning_refusal_woman">
			<selectors>
				<or>
					<hasName name="ksuc_woman_15" />
					<!-- <hasName name="ksuc_woman_16" />	herecka neprijede-->		
					<hasName name="ksuc_woman_17" />
					<!-- <hasName name="ksuc_woman_18" />	herecka neprijede-->
					<hasName name="ksuc_woman_19" />
					<hasName name="ksuc_woman_2" />
					<hasName name="ksuc_woman_20" />
				</or>
			</selectors>
			<operations>
				<addRole name="ZENA_SUCHDOL_O_JIDLE" />
			</operations>
		</rule>

		<rule name="hladAZmar_goodLuck_refusal_man">
			<selectors>
				<or>
					<!-- <hasName name="ksuc_man_1" />	herec neprijede-->
					<hasName name="ksuc_man_17" />
					<!-- <hasName name="ksuc_man_2" />	herec neprijede-->
					<hasName name="ksuc_man_34" />	
					<hasName name="hladAZmar_prepareToLeave_guard4" />	
					<hasName name="hladAZmar_prepareToLeave_guard1" />	
					<hasName name="hladAZmar_prepareToLeave_guard3" />	
					<hasName name="hladAZmar_prepareToLeave_guard2" />
				</or>
			</selectors>
			<operations>
				<addRole name="MUZ_SUCHDOL_LOUCENI_PRED_ODCHODEM" />
			</operations>
		</rule>

		<rule name="hladAZmar_goodLuck_refusal_woman">
			<selectors>
				<or>
					<hasName name="ksuc_woman_15" />
					<!-- <hasName name="ksuc_woman_16" />	herecka neprijede-->		
					<hasName name="ksuc_woman_17" />
					<!-- <hasName name="ksuc_woman_18" />	herecka neprijede-->
					<hasName name="ksuc_woman_19" />
					<hasName name="ksuc_woman_2" />
					<hasName name="ksuc_woman_20" />
				</or>
			</selectors>
			<operations>
				<addRole name="ZENA_SUCHDOL_LOUCENI_PRED_ODCHODEM" />
			</operations>
		</rule>


 	    </rules>
</storm>

=== 7H3LaughingMan/KCD2-Game-Data/Data/Libs/Storm/equipment/quests/fistfightsHorany.xml
<?xml version="1.0"?>
<!DOCTYPE storm SYSTEM "..\storm.dtd">
<storm>
	<rules>

		<rule name="inventory_fistfightsHorany_beruska" Mode="and">
			<selectors>
				<hasName Name="kgru_man_53" />
			</selectors>
			<operations>
				<setInventory preset="inventory_fistfightsHorany_beruska" />
			</operations>
		</rule>

		<rule name="inventory_fistfightsHorany_tuma" Mode="and">
			<selectors>
				<hasName Name="khor_man_1" />
			</selectors>
			<operations>
				<setInventory preset="inventory_fistfightsHorany_tuma" />
			</operations>
		</rule>

		<rule name="inventory_fistfightsHorany_stanik" Mode="and">
			<selectors>
				<hasName Name="khor_man_24" />
			</selectors>
			<operations>
				<setInventory preset="inventory_fistfightsHorany_stanik" />
			</operations>
		</rule>

	</rules>
</storm>
