=== 7H3LaughingMan/KCD2-Game-Data/Data/Libs/Storm/storm.dtd
<?xml version="1.0" standalone="yes" ?>

<!ELEMENT storm (customSelectors?,rules?) >
<!ELEMENT customSelectors (customSelector*) >
<!ATTLIST customSelector name CDATA #IMPLIED mode CDATA #IMPLIED >


<!ELEMENT rules (rule*)>

<!ELEMENT rule (selectors,operations)>
<!ATTLIST rule name CDATA #IMPLIED >


<!ELEMENT operations (addRole*,removeRole*)>

<!ELEMENT selectors (not|or|and|hasFaction|hasGender|hasHobby|hasName|hasShop|hasSuperfaction)*>
<!ELEMENT customSelector (not|or|and|hasFaction|hasGender|hasHobby|hasName|hasShop|hasSuperfaction)*>
<!ELEMENT or (not|or|and|hasFaction|hasGender|hasHobby|hasName|hasShop|hasSuperfaction)* >
<!ELEMENT and (not|or|and|hasFaction|hasGender|hasHobby|hasName|hasShop|hasSuperfaction)* >
<!ELEMENT not (not|or|and|hasFaction|hasGender|hasHobby|hasName|hasShop|hasSuperfaction)* >

<!ELEMENT hasFaction EMPTY >
<!ATTLIST hasFaction faction CDATA #IMPLIED >
<!ELEMENT hasGender EMPTY >
<!ATTLIST hasGender gender CDATA #IMPLIED >
<!ELEMENT hasHobby EMPTY >
<!ATTLIST hasHobby hobby CDATA #IMPLIED >
<!ELEMENT hasShop EMPTY >
<!ELEMENT hasName EMPTY >
<!ATTLIST hasName name CDATA #IMPLIED >

<!ELEMENT addRole EMPTY>
<!ATTLIST addRole name CDATA #IMPLIED >
<!ELEMENT removeRole EMPTY>
<!ATTLIST removeRole name CDATA #IMPLIED >

=== 7H3LaughingMan/KCD2-Game-Data/Data/Libs/Storm/roles/quests/kovarskaSoutez.xml
<?xml version="1.0"?>
<!DOCTYPE storm SYSTEM "../storm.dtd">
<storm>
	<rules>

		<rule name="kovarskaSoutez_ucednikMatej">
			<selectors>
				<hasName name="kgru_matej" />
			</selectors>
			<operations>
				<addRole name="MATEJ" />
			</operations>
		</rule>
		
		<rule name="kovarskaSoutez_kovarZdimir">
			<selectors>
				<hasName name="kgru_zdimir" />
			</selectors>
			<operations>
				<addRole name="ZDIMIR" />
			</operations>
		</rule>
		
		<rule name="kovarskaSoutez_kovarZdimirWatcher">
			<selectors>
				<hasName name="kgru_zdimir" />
			</selectors>
			<operations>
				<addRole name="ZDIMIR_SOUBOJOVE_BARKY" />
			</operations>
		</rule>

		<rule name="kovarskaSoutez_tipster_muz">
			<selectors>
				<hasName name="kgru_gros" />
			</selectors>
			<operations>
				<addRole name="QUEST_TIPSTER_KOVOSOUTEZ_MUZ" />
			</operations>
		</rule>

		<rule name="kovarskaSoutez_tipster_zena">
			<selectors>
				<hasName name="ksta_innkeeper" />
			</selectors>
			<operations>
				<addRole name="QUEST_TIPSTER_KOVOSOUTEZ_NEMKA" />
			</operations>
		</rule>
		
    </rules>
</storm>

=== 7H3LaughingMan/KCD2-Game-Data/Data/Libs/Storm/roles/quests/setkaniVRatbori2.xml
<?xml version="1.0"?>
<!DOCTYPE storm SYSTEM "../storm.dtd">
<storm>
	<rules>
		<rule name="setkaniVRatbori2_ratborDrunk">
			<selectors>
				<and>
					<hasName name="setkaniVRatbori1_ratiborNoble*" />
					<isMan />
				</and>
			</selectors>
			<operations>
				<addRole name="RATBOR_OPILE_GREETINGY" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_ratborReactionToSingingMen">
			<selectors>
				<and>
					<hasName name="setkaniVRatbori1_ratibor*" />
					<isMan />
				</and>
			</selectors>
			<operations>
				<addRole name="RATBOR_REAKCE_NA_ZPEV_MUZ" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_ratborReactionToSingingWomen">
			<selectors>
				<and>
					<hasName name="setkaniVRatbori1_ratibor*" />
					<isWoman />
				</and>
			</selectors>
			<operations>
				<addRole name="RATBOR_REAKCE_NA_ZPEV_ZENA" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_annaZValdstejna">
			<selectors>
				<hasName name="kkut_annaZValdstejna" />
			</selectors>
			<operations>
				<addRole name="ANNA_Z_VALDSTEJNA" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_helena">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNobleWoman1" />
			</selectors>
			<operations>
				<addRole name="HELENA_Z_DVORCE" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_kristyna">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNobleWoman2" />
			</selectors>
			<operations>
				<addRole name="KRISTYNA_Z_NOSTIC" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_matylda">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNobleWoman3" />
			</selectors>
			<operations>
				<addRole name="MATYLDA_ZE_SLAVIC" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_femaleCowards">
			<selectors>
				<and>
					<hasName name="setkaniVRatbori1_*" />
					<isWoman />
				</and>
			</selectors>
			<operations>
				<addRole name="KRCICI_SE_ZENA" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_pacholek">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborHorsetrader2" />
			</selectors>
			<operations>
				<addRole name="PACHOLEK_RATBOR_POSILY" />
				<addRole name="STOLBA_RATBOR" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_MaidsWineHint">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborMaid*" />
			</selectors>
			<operations>
				<addRole name="SLUZEBNA_RATBOR" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_pissedMaid">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborMaid2" />
			</selectors>
			<operations>
				<addRole name="SLUZKA_SE_SMETAKEM" />
				<addRole name="SLUZEBNA_ELISKA_RATBOR" />
				<addRole name="DEVECKA_RATBOR_2" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_prayingMaid">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborMaid1" />
			</selectors>
			<operations>
				<addRole name="DEVECKA_RATBOR_1" />
				<addRole name="KUCHARKA_MADLA_RATBOR" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_maid5">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborMaid5" />
			</selectors>
			<operations>
				<addRole name="SLUZEBNA_DASA_RATBOR" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_intimateMaid">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborMaid4" />
			</selectors>
			<operations>
				<addRole name="SLUZKA_U_PREVETU" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_intimateGuard">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborGuard5" />
			</selectors>
			<operations>
				<addRole name="UZIVAJICI_SI_STRAZNY" />
			</operations>
		</rule>
		
		<rule name="setkaniVRatbori2_flirtatingGuard">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborGuard16" />
			</selectors>
			<operations>
				<addRole name="VOJAK_RATBOR" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_tableDlgGuard1">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborGuard1" />
			</selectors>
			<operations>
				<addRole name="STRAZ_U_STOLU_1" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_barrelDlgNoble6">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble6" />
			</selectors>
			<operations>
				<addRole name="SLECHTIC_U_SOUDKU_1" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_barrelDlgNoble7">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble7" />
			</selectors>
			<operations>
				<addRole name="SLECHTIC_U_SOUDKU_2" />
				<addRole name="OPILY_SLECHTIC_V_SINI_1" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_tableDlgNoble8">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble8" />
			</selectors>
			<operations>
				<addRole name="SLECHTIC_U_STOLU_V_KUCHYNI_1" />
				<addRole name="OPILY_SLECHTIC_V_SINI_2" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_tableDlgNoble9">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble9" />
			</selectors>
			<operations>
				<addRole name="SLECHTIC_U_STOLU_V_KUCHYNI_2" />
				<addRole name="OPILY_SLECHTIC_S_VINI_3" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_tableDlgNoble10">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble10" />
			</selectors>
			<operations>
				<addRole name="SLECHTIC_U_STOLU_V_KUCHYNI_3" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_mainHallDlgGuard3">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborGuard3" />
			</selectors>
			<operations>
				<addRole name="OPILY_STRAZNY_1" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_mainHallDlgGuard4">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborGuard4" />
			</selectors>
			<operations>
				<addRole name="OPILY_STRAZNY_2" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_deadHorseDlgNoble11">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble11" />
			</selectors>
			<operations>
				<addRole name="SLECHTIC_U_KONE_1" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_drunkDlgNoble16">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble16" />
			</selectors>
			<operations>
				<addRole name="OPILY_SLECHTIC_1" />
				<addRole name="SLECHTIC_U_KONE_2" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_drunkDlgNoble17">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble17" />
			</selectors>
			<operations>
				<addRole name="OPILY_SLECHTIC_2" />
				<addRole name="SLECHTIC_U_KONE_3" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_tableDlgNoble1">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble12" />
			</selectors>
			<operations>
				<addRole name="SLECHTIC_U_STOLU_1" />
				<addRole name="SLECHTIC_NA_LAVICI_V_SINI_1" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_tableDlgNoble2">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble13" />
			</selectors>
			<operations>
				<addRole name="SLECHTIC_U_STOLU_2" />
				<addRole name="SLECHTIC_NA_LAVICI_V_SINI_2" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_beerDrinker1">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble2" />
			</selectors>
			<operations>
				<addRole name="PIVAR_1" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_beerDrinker2">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborNoble3" />
			</selectors>
			<operations>
				<addRole name="PIVAR_2" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_tableDlgGuard2">
			<selectors>
				<hasName name="setkaniVRatbori1_ratiborGuard2" />
			</selectors>
			<operations>
				<addRole name="STRAZ_U_STOLU_2" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_BohutaPray">
			<selectors>
				<hasName name="tneb_bohuta" />
			</selectors>
			<operations>
				<addRole name="BOHUTA_NPC_MODLI_SE" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_zizkaYellAtBohuta">
			<selectors>
				<hasName name="tneb_zizka" />
			</selectors>
			<operations>
				<addRole name="ZIZKA_VOLA_V_BOJI_NA_BOHUTU" />
				<addRole name="ZIZKA_DOSTAL_ZASAH_RATBOR" />
				<addRole name="ZIZKA_ZASAHL_NEPRITELE_RATBOR" />
			</operations>
		</rule>

		<rule name="setkaniVRatbori2_haggleWithEliska">
 			<selectors>
    			<hasName name="setkaniVRatbori1_ratiborMaid2"/>
  			</selectors>
			<operations>
    			<addRole name="VYJEDNAVANI_ZENA"/>
  			</operations>
		</rule>

		<rule name="setkaniVRatbori2_enemyCommander">
 			<selectors>
    			<hasName name="setkaniVRatbori2_court_enemy_soldier_1"/>
  			</selectors>
			<operations>
    			<addRole name="RATBOR_VELITEL_UTOCNIKU"/>
  			</operations>
		</rule>
    </rules>
</storm>

=== 7H3LaughingMan/KCD2-Game-Data/Data/Libs/Storm/equipment/quests/poustevnik.xml
<?xml version="1.0"?>
<!DOCTYPE storm SYSTEM "..\storm.dtd">
<storm>
	<rules>

		<rule name="inventory_poustevnik_ambroz" Mode="and">

			<selectors>
				<hasName Name="tapo_ambroz" />
			</selectors>

			<operations>
				<setInventory preset="inventory_poustevnik" />
			</operations>

		</rule>

		<rule name="inventory_poustevnik_konrad" Mode="and">

			<selectors>
				<hasName Name="tapo_konrad" />
			</selectors>

			<operations>
				<setInventory preset="inventory_poustevnik_konrad" />
			</operations>

		</rule>
        
        
        		<rule name="inventory_poustevnik_niclas" Mode="and">

			<selectors>
				<hasName Name="poustevnik_niclas" />
			</selectors>

			<operations>
				<setInventory preset="inventory_niclas" />
			</operations>

		</rule>
        
        		<rule name="inventory_poustevnik_sebald" Mode="and">

			<selectors>
				<hasName Name="poustevnik_sebald" />
			</selectors>

			<operations>
				<setInventory preset="inventory_sebald" />
			</operations>

		</rule>
        
        		<rule name="inventory_poustevnik_arn" Mode="and">

			<selectors>
				<hasName Name="poustevnik_arn" />
			</selectors>

			<operations>
				<setInventory preset="inventory_arn" />
			</operations>

		</rule>
        
        		<rule name="inventory_poustevnik_clesgin" Mode="and">

			<selectors>
				<hasName Name="poustevnik_clesgin" />
			</selectors>

			<operations>
				<setInventory preset="inventory_clesgin" />
			</operations>

		</rule>


	</rules>
</storm>

=== 7H3LaughingMan/KCD2-Game-Data/Data/Libs/Storm/equipment/world/equipment_khor.xml
<?xml version="1.0"?>
<!DOCTYPE storm SYSTEM "..\storm.dtd">
<storm>
  <rules>

    <rule name="inventory_khor_oreseller" Mode="and">
        <selectors>
            <hasName name="khor_oreseller" />
        </selectors>
        <operations>
            <setInventory preset="inventory_khor_oreseller" />
        </operations>
    </rule>

    <rule name="inventory_khor_kristianZPisku" Mode="and">
			<selectors>
				<hasName name="khor_kristianZPisku" />
			</selectors>

			<operations>
				<setInventory preset="inventory_khor_kristianZPisku" />
			</operations>
		</rule>

		<rule name="inventory_khor_thomlin" Mode="and">
			<selectors>
				<hasName name="khor_thomlin" />
			</selectors>
			<operations>
				<setInventory preset="inventory_khor_thomlin" />
			</operations>
		</rule>

   
  </rules>
</storm>

=== 7H3LaughingMan/KCD2-Game-Data/Data/Libs/Storm/roles/events/rvacka.xml
<?xml version="1.0"?>
<!DOCTYPE storm SYSTEM "../../storm.dtd">
<storm>
  <rules>
    <!-- Guards reaction -->
		<rule name="rvacka_guards">
			<selectors>
				<isAuthorityFigure />
			</selectors>
			<operations>
				<addRole name="EVENT_RVACKA_STRAZ" />
			</operations>
		</rule>

    <rule name="rvacka_common">
      <selectors>
        <hasName name="rvacka_*" />
        <not>
          <isCuman />
        </not>
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_PORAZENY" />
        <addRole name="EVENT_RVACKA_VITEZ" />        
      </operations>
    </rule>
    

    <!-- Drunkard -->
    <rule name="rvacka_drunkard">
      <selectors>
        <hasName name="rvacka_drunkard" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_OPILEC" />
      </operations>
    </rule>
    <rule name="rvacka_bouncer_1">
      <selectors>
        <hasName name="rvacka_bouncer_1" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_VYHAZOVAC_1" />
      </operations>
    </rule>
    <rule name="rvacka_bouncer_2">
      <selectors>
        <hasName name="rvacka_bouncer_2" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_VYHAZOVAC_2" />
      </operations>
    </rule>

    <!-- Cheater -->
    <rule name="rvacka_cheater">
      <selectors>
        <hasName name="rvacka_cheater" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_PODVADEJICI_HRAC" />
      </operations>
    </rule>
    <rule name="rvacka_player_1">
      <selectors>
        <hasName name="rvacka_player_1" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_HRAC_1" />
      </operations>
    </rule>
    <rule name="rvacka_player_2">
      <selectors>
        <hasName name="rvacka_player_2" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_HRAC_2" />
      </operations>
    </rule>

    <!-- Jealous -->
    <rule name="rvacka_voyeur">
      <selectors>
        <hasName name="rvacka_voyeur" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_CUMIL" />
      </operations>
    </rule>
    <rule name="rvacka_jealous">
      <selectors>
        <hasName name="rvacka_jealous" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_ZARLIVEC" />
      </operations>
    </rule>
    <rule name="rvacka_girl">
      <selectors>
        <hasName name="rvacka_girl" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_SLECNA" />
      </operations>
    </rule>

    <!-- HoneyPie -->
    <rule name="rvacka_apprentice_1">
      <selectors>
        <hasName name="rvacka_apprentice_1" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_TOVARYS_1" />
      </operations>
    </rule>
    <rule name="rvacka_apprentice_2">
      <selectors>
        <hasName name="rvacka_apprentice_2" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_TOVARYS_2" />
      </operations>
    </rule>
    <rule name="rvacka_apprentice_3">
      <selectors>
        <hasName name="rvacka_apprentice_3" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_TOVARYS_3" />
      </operations>
    </rule>

    <!-- Neighbours -->
    <rule name="rvacka_neighbour_1">
      <selectors>
        <hasName name="rvacka_neighbour_1" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_SOUSED_1" />
      </operations>
    </rule>
    <rule name="rvacka_neighbour_2">
      <selectors>
        <hasName name="rvacka_neighbour_2" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_SOUSED_2" />
      </operations>
    </rule>  

    <!-- Generic czech -->
    <rule name="rvacka_generic_firstCzech">
      <selectors>
        <hasName name="rvacka_firstCzech_*" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_CECH_1" />
      </operations>
    </rule>

    <rule name="rvacka_generic_secondCzech">
      <selectors>
        <hasName name="rvacka_secondCzech_*" />
      </selectors>
      <operations>
        <addRole name="EVENT_RVACKA_CECH_2" />
      </operations>
    </rule>    

    <!-- Generic cuman -->
		<rule name="rvacka_generic_cuman">
      <selectors>
        <hasName name="rvacka_cuman_*" />
      </selectors>
			<operations>
				<addRole name="EVENT_RVACKA_KUMAN_1" />		
				<addRole name="EVENT_RVACKA_KUMAN_2" />
			</operations>
		</rule>    

  </rules>
</storm>

=== 7H3LaughingMan/KCD2-Game-Data/Data/Libs/Storm/equipment/world/equipment_tkop.xml
<?xml version="1.0"?>
<!DOCTYPE storm SYSTEM "..\storm.dtd">
<storm>
  <rules>

    <rule name="inventory_tkop_man_1" Mode="and">
      <selectors>
        <hasName name="tkop_man_1" />
      </selectors>
      <operations>
        <setInventory preset="inventory_tkop_man_1" />
      </operations>
    </rule>

    <rule name="inventory_tkop_man_2" Mode="and">
      <selectors>
        <hasName name="tkop_man_2" />
      </selectors>
      <operations>
        <setInventory preset="inventory_tkop_man_2" />
      </operations>
    </rule>

  </rules>
</storm>

=== 7H3LaughingMan/KCD2-Game-Data/Data/Libs/Storm/equipment/quests/erik.xml
<?xml version="1.0"?>
<!DOCTYPE storm SYSTEM "..\storm.dtd">
<storm>
	<rules>

		<rule name="inventory_erik_suchdol_gate_guard">
			<selectors>
				<hasName Name="erik_guard" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_guard" />
			</operations>
		</rule>

		<rule name="inventory_erik_suchdol_party_soldier_barrel">
			<selectors>
				<hasName Name="erik_party_barrelMan_1" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_party_soldier_barrel" />
			</operations>
		</rule>

		<rule name="inventory_erik_suchdol_party_soldier_dancer">
			<selectors>
				<hasName Name="erik_party_dancerMan_1" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_party_soldier_dancer" />
			</operations>
		</rule>

		<rule name="inventory_erik_suchdol_party_soldier_sitting">
			<selectors>
				<hasName Name="erik_party_sittingGroupMan_2" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_party_soldier_sitter" />
			</operations>
		</rule>

		<rule name="inventory_erik_suchdol_party_dancerWoman_1">
			<selectors>
				<hasName Name="erik_party_dancerWoman_1" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_party_dancerWoman_1" />
			</operations>
		</rule>

		<rule name="inventory_erik_suchdol_party_dancerWoman_2">
			<selectors>
				<hasName Name="erik_party_dancerWoman_2" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_party_dancerWoman_2" />
			</operations>
		</rule>

		<rule name="inventory_erik_suchdol_vozka">
			<selectors>
				<hasName Name="erik_vozka" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_vozka" />
			</operations>
		</rule>

		<rule name="inventory_erik_suchdol_party_muscian_1">
			<selectors>
				<hasName Name="erik_party_musician_1" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_party_musician_1" />
			</operations>
		</rule>

		<rule name="inventory_erik_suchdol_party_muscian_2">
			<selectors>
				<hasName Name="erik_party_musician_2" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_party_musician_2" />
			</operations>
		</rule>

		<rule name="inventory_erik_party_groupMan_1">
			<selectors>
				<hasName Name="erik_party_groupMan_1" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_party_groupMan_1" />
			</operations>
		</rule>

		<rule name="inventory_erik_party_groupMan_2">
			<selectors>
				<hasName Name="erik_party_groupMan_2" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_party_groupMan_2" />
			</operations>
		</rule>

		<rule name="inventory_erik_party_sittingGroupMan_1">
			<selectors>
				<hasName Name="erik_party_sittingGroupMan_1" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_party_sittingGroupMan_1" />
			</operations>
		</rule>

		<rule name="inventory_erik_party_groupWoman_1">
			<selectors>
				<hasName Name="erik_party_groupWoman_1" />
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_party_groupWoman_1" />
			</operations>
		</rule>

		<rule name="inventory_erik_soldier">
			<selectors>
				<or>
					<hasName Name="erik_soldier1" />
					<hasName Name="erik_soldier2" />
					<hasName Name="erik_soldier3" />
				</or>
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_soldier" />
			</operations>
		</rule>

		<rule name="inventory_erik_horse">
			<selectors>
				<or>
					<hasName Name="erik_soldier_horse1" />
					<hasName Name="erik_soldier_horse2" />
					<hasName Name="erik_soldier_horse3" />
					<hasName Name="erik_cavalryHorse*" />
				</or>
			</selectors>
			<operations>
				<setInventory preset="horse_prague" />
			</operations>
		</rule>

		<rule name="inventory_erik_animchar_heavy">
			<selectors>
				<or>
					<hasName Name="erik_cavalryGroup1_soldier*" />
					<hasName Name="erik_cavalryGroup2_soldier*" />
					<hasName Name="erik_cavalryGroup3_soldier*" />
					<hasName Name="erik_cavalryGroup4_soldier*" />
					<hasName Name="erik_cavalryGroup5_soldier*" />
					<hasName Name="erik_cavalryGroup6_soldier*" />
				</or>
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_soldier_animchar_heavy" />
			</operations>
		</rule>

		<rule name="inventory_erik_animchar_light">
			<selectors>
				<or>
					<hasName Name="erik_cavalryGroup1_scout*" />
					<hasName Name="erik_infantryGroup1_soldier*" />
				</or>
			</selectors>
			<operations>
				<setInventory preset="inventory_erik_soldier_animchar_light" />
			</operations>
		</rule>



	</rules>
</storm>
